### ISSUE TITLE
Notification's time runs endlessly and disappear after pauses the same song.

### ISSUE THREAD

**Issue by skmaiti2050** [teocci/YouTube-In-Background#10]
Google account sign in doesn't work, verified with 2 different devices, still no such interface shows up. So playlists doesn't work.

If not paused, the notification keeps on showing time either from 00:00 or else time after the song time ends and runs endlessly with no audio.

After 2 or 3 pauses to a same music makes the notification disappear, and the music is shown still playing in the app without any audio and control buttons of the player in the app doesn't work i.e. pause doesn't work. Anyways keep the great work up, thanks @teocci for fixing pause bug :)

**Comment by skmaiti2050** [comment]
Issue reference that might help:
https://github.com/google/ExoPlayer/issues/5301
https://github.com/google/ExoPlayer/issues/5117

**Comment by teocci** [comment]
@skmaiti2050 could you please move the Sign bug to another issue. I renamed this issue as "Notification's time runs endlessly and disappear after pauses the same song."

**Comment by teocci** [comment]
Fixed in the new release 3.1.1
